export const LOGIN_USER_START = 'LOGIN_USER_START';
export const ERROR_USER_LOGIN = 'ERROR_USER_LOGIN';
export const LOGIN_USER_END = 'LOGIN_USER_END';
export const REFRESH_TOKEN_END = 'REFRESH_TOKEN_END';
export const ERROR_REFRESH_TOKEN = 'ERROR_REFRESH_TOKEN';